---
name: Add Changelog File

on:
  workflow_dispatch:

jobs:
  changelog_creation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        ssh-key: ${{ secrets.DEPLOYKEY_PRIVATE }}
    - name: Create CHANGELOG.yaml
      run: |
        chmod +x ./changelog-generator.sh
        ./changelog-generator.sh
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Changelog"
        git push
